### ISSUE TITLE
Discuss Github actions pipeline & pre-commit hooks

### ISSUE THREAD

**Issue by marcluque** [Benzammour/yobemag#16]
Since we are accumulating more and more tools for analysis, tests, etc. we could have a discussion what order jobs in the pipeline should run.

I propose the following chain of jobs for PRs:

 `build` -> `static analysis` -> `unit tests` -> `sonarcloud`

Linting is done via pre-commit hooks.

The reasoning behind this order (and dependencies) is the following: 
- build should only be done when coding conventions are correctly done (enforced by pre-commit hooks)
- (most) static analysis requires error-free compilation
- unit tests (i.e., dynamic analysis) is done after potential bugs are removed
- lastly, sonarcloud can be executed once the unit tests are done to collect the code coverage and do a final analysis

A breakdown of the jobs:
- lint (technically not a job, but a pre-commit hook):
  - clang-format linting
  - clang-tidy linting
  - https://pre-commit.com/
- build:
  - CMake build
- static analysis (list of some tools, any amount is fine):
  - Cppcheck
  - Clang Static Analyzer
- unit tests:
  - CMake build of Criterion test suite
- sonarcloud

TODOs for this issue:

- [x] prepare pre-commit linting hooks (#27)
- [x] add static analysis job with desired tool (#13)
- [x] add job for running test suite (#13)
- [x] lastly chain all jobs together (#13)
- [x] add gcov to pipeline to report coverage to sonarcloud (#19)

**Comment by Benzammour** [comment]
The order looks good to me, but I would add additional pre-commit hooks, that enforce the `lint` rules.
This enables us to keep our code clean before committing (via pre-commit hooks), as well as notify us if someone down the line (unknowingly) omits our format rules (via pipeline).

**Comment by marcluque** [comment]
That is true, that should be better!
